import { MenuType } from '@/modules/rbac/constants'

export type MenuItem = {
    label: string
    name: string
    type: MenuType
    icon?: string
    customOrder?: number
    isFrame?: boolean
    frameSrc?: string
    isCache?: boolean
    path: string
    component?: string
    perms?: string
    query?: string
    hide?: boolean
    status?: number
    newFeature?: boolean
    hideTab?: boolean
    parent?: string | null
    children?: MenuItem[]
}

export const MENUS: MenuItem[] = [
    {
        label: 'sys.menu.dashboard',
        name: 'Dashboard',
        type: MenuType.CATALOGUE,
        icon: 'ic-analysis',
        path: 'dashboard',
        children: [
            {
                label: 'sys.menu.workbench',
                name: 'Workbench',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'workbench',
                component: '/dashboard/workbench/index.tsx',
            },
            {
                label: 'sys.menu.analysis',
                name: 'Analysis',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'analysis',
                component: '/dashboard/analysis/index.tsx',
            },
        ],
    },
    {
        label: 'sys.menu.management',
        name: 'Management',
        icon: 'ic-management',
        type: MenuType.CATALOGUE,
        path: 'management',
        children: [
            {
                label: 'sys.menu.system.user',
                name: 'User',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'user',
                component: '/management/system/user/index.tsx',
            },
            {
                label: 'sys.menu.system.role',
                name: 'Role',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'role',
                component: '/management/system/role/index.tsx',
            },
            {
                label: 'sys.menu.system.menu',
                name: 'Menu',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'menu',
                component: '/management/system/menu/index.tsx',
            },
            {
                label: 'sys.menu.system.dict',
                name: 'Dict',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'dict',
                component: '/management/system/dict/index.tsx',
            },
            {
                label: 'sys.menu.system.dictData',
                name: 'Dict Data',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'dict/:id',
                hide: true,
                component: '/management/system/dict/data.tsx',
            },
            {
                label: 'sys.menu.system.token',
                name: 'Token',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'token',
                component: '/management/system/token/index.tsx',
            },
        ],
    },
    {
        label: 'sys.menu.user.index',
        name: 'User',
        type: MenuType.CATALOGUE,
        hide: true,
        path: 'user',
        children: [
            {
                label: 'sys.menu.user.profile',
                name: 'Profile',
                type: MenuType.MENU,
                path: 'profile',
                hide: true,
                component: '/management/user/profile/index.tsx',
            },
            {
                label: 'sys.menu.user.account',
                name: 'Account',
                type: MenuType.MENU,
                path: 'account',
                hide: true,
                component: '/management/user/account/index.tsx',
            },
        ],
    },
    {
        label: 'sys.menu.content.index',
        name: 'Content',
        icon: 'ic_content',
        type: MenuType.CATALOGUE,
        path: 'content',
        children: [
            {
                label: 'sys.menu.content.post',
                name: 'Post',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'posts',
                component: '/content/posts/index.tsx',
            },
            {
                label: 'sys.menu.content.create-post',
                name: 'Create Post',
                type: MenuType.MENU,
                hide: true,
                icon: 'ic_dot',
                path: 'create-post',
                component: '/content/posts/create.tsx',
            },
            {
                label: 'sys.menu.content.categories',
                name: 'Categories',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'categories',
                component: '/content/categories/index.tsx',
            },
            {
                label: 'sys.menu.content.tags',
                name: 'Tags',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'tags',
                component: '/content/tags/index.tsx',
            },
            {
                label: 'sys.menu.content.comments',
                name: 'Comments',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'comments',
                component: '/content/comments/index.tsx',
            },
        ],
    },
    {
        label: 'sys.menu.frame',
        name: 'Frame',
        icon: 'ic_external',
        type: MenuType.CATALOGUE,
        path: 'frame',
        children: [
            {
                label: 'sys.menu.external_link',
                name: 'External Link',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'external_link',
                hideTab: true,
                component: '/sys/others/iframe/external-link.tsx',
                isFrame: true,
                frameSrc: 'https://ant.design/',
            },
            {
                label: 'sys.menu.iframe',
                name: 'Iframe',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'frame',
                component: '/sys/others/iframe/index.tsx',
                isFrame: true,
                frameSrc: 'https://docs.nestjs.com/',
            },
        ],
    },
    {
        label: 'sys.menu.logs.index',
        name: 'Logs',
        icon: 'ic_log',
        type: MenuType.CATALOGUE,
        path: 'log',
        children: [
            {
                label: 'sys.menu.logs.login-log',
                name: 'Login Log',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'login-log',
                component: '/logs/login/index.tsx',
            },
            {
                label: 'sys.menu.logs.operation-log',
                name: 'Operation Log',
                type: MenuType.MENU,
                icon: 'ic_dot',
                path: 'operation-log',
                component: '/logs/operation/index.tsx',
            },
        ],
    },
    {
        label: 'sys.menu.display',
        name: 'Display',
        icon: 'solar:plain-2-bold-duotone',
        type: MenuType.CATALOGUE,
        path: 'display',
        children: [
            {
                label: 'sys.menu.calendar',
                name: 'Calendar',
                icon: 'solar:calendar-bold-duotone',
                type: MenuType.MENU,
                path: 'calendar',
                component: '/sys/others/calendar/index.tsx',
            },
            {
                label: 'sys.menu.kanban',
                name: 'kanban',
                icon: 'solar:clipboard-bold-duotone',
                type: MenuType.MENU,
                path: 'kanban',
                component: '/sys/others/kanban/index.tsx',
            },
            {
                label: 'sys.menu.disabled',
                name: 'Disabled',
                icon: 'ic_disabled',
                type: MenuType.MENU,
                path: 'disabled',
                status: 0,
                component: '/sys/others/calendar/index.tsx',
            },
            {
                label: 'sys.menu.label',
                name: 'Label',
                icon: 'ic_label',
                type: MenuType.MENU,
                path: 'label',
                newFeature: true,
                component: '/sys/others/blank.tsx',
            },
            {
                label: 'sys.menu.blank',
                name: 'Blank',
                icon: 'ic_blank',
                type: MenuType.MENU,
                path: 'blank',
                component: '/sys/others/blank.tsx',
            },
            {
                label: 'sys.menu.error.index',
                name: 'Error',
                icon: 'bxs:error-alt',
                type: MenuType.CATALOGUE,
                path: 'error',
                children: [
                    {
                        label: 'sys.menu.error.403',
                        name: '403',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: '403',
                        component: '/sys/error/Page403.tsx',
                    },
                    {
                        label: 'sys.menu.error.404',
                        name: '404',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: '404',
                        component: '/sys/error/Page404.tsx',
                    },
                    {
                        label: 'sys.menu.error.500',
                        name: '500',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: '500',
                        component: '/sys/error/Page500.tsx',
                    },
                ],
            },
            {
                label: 'sys.menu.components',
                name: 'Components',
                icon: 'solar:widget-5-bold-duotone',
                type: MenuType.CATALOGUE,
                path: 'components',
                children: [
                    {
                        label: 'sys.menu.icon',
                        name: 'Icon',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: 'icon',
                        component: '/components/icon/index.tsx',
                    },
                    {
                        label: 'sys.menu.animate',
                        name: 'Animate',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: 'animate',
                        component: '/components/animate/index.tsx',
                    },
                    {
                        label: 'sys.menu.scroll',
                        name: 'Scroll',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: 'scroll',
                        component: '/components/scroll/index.tsx',
                    },
                    {
                        label: 'sys.menu.markdown',
                        name: 'Markdown',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: 'markdown',
                        component: '/components/markdown/index.tsx',
                    },
                    {
                        label: 'sys.menu.editor',
                        name: 'Editor',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: 'editor',
                        component: '/components/editor/index.tsx',
                    },
                    {
                        label: 'sys.menu.i18n',
                        name: 'Multi Language',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: 'i18n',
                        component: '/components/multi-language/index.tsx',
                    },
                    {
                        label: 'sys.menu.upload',
                        name: 'upload',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: 'Upload',
                        component: '/components/upload/index.tsx',
                    },
                    {
                        label: 'sys.menu.chart',
                        name: 'Chart',
                        type: MenuType.MENU,
                        icon: 'ic_dot',
                        path: 'chart',
                        component: '/components/chart/index.tsx',
                    },
                ],
            },
        ],
    },
    {
        label: 'sys.menu.about',
        name: 'About',
        type: MenuType.MENU,
        icon: 'ic_about',
        path: 'about',
        component: '/about/index.tsx',
    },
]
